
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri May 23 19:33:16 CST 2025
//----------------------------------------------------

package View;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OpeningBracket = 8;
  public static final int lFor = 20;
  public static final int sBreak = 22;
  public static final int sAbstract = 63;
  public static final int BOOL = 6;
  public static final int sForeach = 34;
  public static final int Brackets = 47;
  public static final int boolConstant = 39;
  public static final int sReadInteger = 28;
  public static final int sPrint = 23;
  public static final int sPrivate = 56;
  public static final int sMalloc = 29;
  public static final int negative = 43;
  public static final int ClosedBracket = 9;
  public static final int ident = 2;
  public static final int stringConstant = 40;
  public static final int OpeningParenthesis = 10;
  public static final int dot = 30;
  public static final int sTry = 68;
  public static final int namespaceName = 53;
  public static final int DOUBLE = 5;
  public static final int sUsing = 52;
  public static final int sVirtual = 61;
  public static final int integerConstant = 37;
  public static final int colon = 64;
  public static final int sSetByte = 32;
  public static final int ArithmeticOperators = 45;
  public static final int ClosedParenthesis = 11;
  public static final int pyc = 3;
  public static final int sParams = 74;
  public static final int or = 49;
  public static final int sSet = 59;
  public static final int IncrementOperator = 66;
  public static final int sGetByte = 31;
  public static final int sRef = 75;
  public static final int cIf = 17;
  public static final int sSwitch = 71;
  public static final int sVoid = 12;
  public static final int ComparisonOperators = 41;
  public static final int sNew = 26;
  public static final int sPublic = 55;
  public static final int sReturn = 21;
  public static final int cElse = 18;
  public static final int and = 48;
  public static final int sNull = 33;
  public static final int sCatch = 69;
  public static final int INT = 4;
  public static final int sThis = 25;
  public static final int comma = 13;
  public static final int EOF = 0;
  public static final int sNameSpace = 54;
  public static final int sNewArray = 27;
  public static final int Parenthesis = 50;
  public static final int assignment = 24;
  public static final int ClosedCurlyBracket = 16;
  public static final int CurlyBrackets = 51;
  public static final int sProtected = 57;
  public static final int error = 1;
  public static final int sDo = 67;
  public static final int doubleConstant = 38;
  public static final int sGet = 58;
  public static final int sReadLine = 36;
  public static final int lWhile = 19;
  public static final int sum = 44;
  public static final int denial = 46;
  public static final int sClass = 14;
  public static final int sDefault = 73;
  public static final int sCase = 72;
  public static final int sFinally = 70;
  public static final int OpeningCurlyBracket = 15;
  public static final int sOverride = 62;
  public static final int STRING = 7;
  public static final int sStatic = 60;
  public static final int sOut = 76;
  public static final int sIn = 35;
  public static final int equality = 42;
  public static final int sInterface = 65;
}

